### ISSUE TITLE
Error installing?!?!?

### ISSUE THREAD

**Issue by cryptid11** [pyca/pynacl#180]
$ sudo python setup.py install

Installed /home/rodomonte/Documents/pynacl/.eggs/cffi-1.5.2-py2.7-linux-x86_64.egg
Traceback (most recent call last):
  File "setup.py", line 259, in <module>
    "Programming Language :: Python :: 3.5",
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 272, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 327, in finalize_options
    ep.load()(self, ep.name, value)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named setuptools_ext

I really don't get it...some help?

**Comment by reaperhulk** [comment]
It doesn't look like cffi is properly being installed despite the egg being present in that first line. `pip install cffi` first and then try installing pynacl.

**Comment by cryptid11** [comment]
Excuse me I just solve it, yes, seems it works after upgrading that interface package. hope this issue will be useful to somebody else, thanks.

**Comment by judge2020** [comment]
This also fixed it for me, came here from google.
