### ISSUE TITLE
Many dependency when install pynacl 

### ISSUE THREAD

**Issue by pyhonda** [pyca/pynacl#324]
Unfortunately, My server not allow access to internet, so I can't use pip3 to install, have to install one by one.
When I install paramiko, it return error pynacl miss, So I download and try to install PyNaCl-1.1.2, but return error: Could not find suitable distribution for Requirement.parse('cffi>=1.4.1').
Any easy way to install pynacl? because when I try to install cffi, then miss libffi error return, too many dependency.
 
============= ERROR when install PyNaCl-1.1.2========================
python setup.py install
Download error on https://pypi.python.org/simple/cffi/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'cffi' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for cffi>=1.4.1
Traceback (most recent call last):
  File "setup.py", line 232, in <module>
    "Programming Language :: Python :: 3.6",
  File "/home/bmcsupport/python3/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/bmcsupport/python3/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/home/bmcsupport/python3/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/bmcsupport/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/home/bmcsupport/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
    return self.obtain(req, installer)
  File "/home/bmcsupport/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
    return installer(requirement)
  File "/home/bmcsupport/python3/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home/bmcsupport/python3/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cffi>=1.4.1')

**Comment by alex** [comment]
`pynacl` depends on `cffi`, which depends on `libffi`. There's not really any way around this.

However, all of these projects ship wheels, so if you install a recent version of `pip`, it should all just work.
