### ISSUE TITLE
pip install pynacl error

### ISSUE THREAD

**Issue by sangli00** [pyca/pynacl#326]
error log
```
CC       crypto_stream/salsa208/ref/libsodium_la-stream_salsa208.lo
      CC       crypto_stream/salsa208/ref/libsodium_la-xor_salsa208.lo
      CC       crypto_aead/aes256gcm/aesni/libaesni_la-aead_aes256gcm_aesni.lo
      CCLD     libaesni.la
    libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
      CC       crypto_pwhash/scryptsalsa208sha256/sse/libsse2_la-pwhash_scryptsalsa208sha256_sse.lo
      CC       crypto_onetimeauth/poly1305/sse2/libsse2_la-poly1305_sse2.lo
      CCLD     libsse2.la
    libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
      CC       crypto_generichash/blake2/ref/libssse3_la-blake2b-compress-ssse3.lo
      CC       crypto_pwhash/argon2/libssse3_la-argon2-fill-block-ssse3.lo
      CC       crypto_stream/chacha20/vec/libssse3_la-stream_chacha20_vec.lo
      CCLD     libssse3.la
    libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
      CC       crypto_generichash/blake2/ref/libsse41_la-blake2b-compress-sse41.lo
      CCLD     libsse41.la
    libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
      CC       crypto_generichash/blake2/ref/libavx2_la-blake2b-compress-avx2.lo
    /tmp/cc1Axjh2.s: Assembler messages:
    /tmp/cc1Axjh2.s:36: Error: no such instruction: `vbroadcasti128 48(%rsi),%ymm7'
    /tmp/cc1Axjh2.s:41: Error: no such instruction: `vbroadcasti128 32(%rsi),%ymm11'
    /tmp/cc1Axjh2.s:51: Error: no such instruction: `vbroadcasti128 (%rsi),%ymm10'
    /tmp/cc1Axjh2.s:56: Error: no such instruction: `vbroadcasti128 16(%rsi),%ymm8'
    /tmp/cc1Axjh2.s:63: Error: suffix or operands invalid for `vpunpcklqdq'
    /tmp/cc1Axjh2.s:70: Error: no such instruction: `vbroadcasti128 112(%rsi),%ymm4'
    /tmp/cc1Axjh2.s:77: Error: suffix or operands invalid for `vpunpcklqdq'
    /tmp/cc1Axjh2.s:96: Error: no such instruction: `vbroadcasti128 96(%rsi),%ymm7'
    /tmp/cc1Axjh2.s:101: Error: no such instruction: `vbroadcasti128 80(%rsi),%ymm6'
    /tmp/cc1Axjh2.s:108: Error: no such instruction: `vpblendd $240,%ymm1,%ymm0,%ymm4'
    /tmp/cc1Axjh2.s:124: Error: suffix or operands invalid for `vpaddq'
    /tmp/cc1Axjh2.s:132: Error: no such instruction: `vbroadcasti128 64(%rsi),%ymm9'
    /tmp/cc1Axjh2.s:140: Error: suffix or operands invalid for `vpaddq'
    /tmp/cc1Axjh2.s:147: Error: suffix or operands invalid for `vpunpcklqdq'
    /tmp/cc1Axjh2.s:154: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm0,%ymm1'
    /tmp/cc1Axjh2.s:161: Error: suffix or operands invalid for `vpunpckhqdq'
    /tmp/cc1Axjh2.s:167: Error: suffix or operands invalid for `vpxor'
    /tmp/cc1Axjh2.s:179: Error: suffix or operands invalid for `vpunpckhqdq'
    /tmp/cc1Axjh2.s:185: Error: suffix or operands invalid for `vpxor'
    /tmp/cc1Axjh2.s:191: Error: no such instruction: `vpblendd $240,%ymm4,%ymm0,%ymm0'
......

```

Traceback
```
make: *** [all-recursive] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bwnTFm/pynacl/setup.py", line 232, in <module>
        "Programming Language :: Python :: 3.6",
      File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python2.6/distutils/command/install.py", line 577, in run
        self.run_command('build')
      File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
        cmd_obj.run()
      File "/usr/lib64/python2.6/distutils/command/build.py", line 134, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-bwnTFm/pynacl/setup.py", line 163, in run
        subprocess.check_call(["make"], cwd=build_temp)
      File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-bwnTFm/pynacl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-MFoF5Y-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-bwnTFm/pynacl/
```

**Comment by sangli00** [comment]
what happen in this error?

**Comment by lmctv** [comment]
Could you please add some info about the runtime environment: operating system, OS version, compiler version etc? Thanks.

**Comment by sangli00** [comment]
centos6.8  I switch to 7.0 is OK. maybe is Python version
