### ISSUE TITLE
Failing to install on Windows MinGW

### ISSUE THREAD

**Issue by robarthur** [pyca/pynacl#377]
Hi I'm seeing the following issue which I think is related to this previously fixed issue:
https://github.com/pyca/pynacl/issues/298

I'm attempting to install running in a MinGW shell (git bash).  I have the make utility installed via chocolatey.  If I run `which make` I can see...
```
$ which make
/c/ProgramData/chocolatey/bin/make
```

I'm seeing the following logs when running pip install:
```
    running build_clib
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-build-e59s3crj\pynacl\setup.py", line 248, in <module>
        "Programming Language :: Python :: 3.6",
      File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\user\AppData\Local\Temp\pip-build-e59s3crj\pynacl\setup.py", line 157, in run
        raise Exception("ERROR: The 'make' utility is missing from PATH")
    Exception: ERROR: The 'make' utility is missing from PATH
```

**Comment by alex** [comment]
Interesting... the  easiest solution is probably to make sure you have an up to date pip, which will ensure a wheel is installed, bypassing this issue.

**Comment by lmctv** [comment]
While I've not been using MinGW since a long time, I think you should take a look at installing the MinGW provided make binary, if are really interested in building PyNaCl with MinGW. Still, I concur with @alex's opinion about using the precompiled wheels with a up to date pip, as the best option.

**Comment by lmctv** [comment]
Documentation on MinGW should come with general solution of  #165 . Closing as a duplicate.
