### ISSUE TITLE
Can't resolve symbol under ARM uClibc

### ISSUE THREAD

**Issue by MrDini123** [pyca/pynacl#402]
Hi,

I have an ARMv5 NAS with uClibc C compiler, and Python 3.5.1. I installed pynacl with pip first, and it gave me this:

```
>>> import nacl.secret

/bin/python3.5: symbol '__stack_chk_guard': can't resolve symbol

/bin/python3.5: symbol '__stack_chk_fail': can't resolve symbol
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.5/site-packages/nacl/secret.py", line 17, in <module>
    import nacl.bindings
  File "/lib/python3.5/site-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_aead import (
  File "/lib/python3.5/site-packages/nacl/bindings/crypto_aead.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ImportError: unknown dlopen() error
```

I also tried to compile manually the latest git version, but the results are the same. Can you please fix it by checking that in the configure script?

Thanks!

**Comment by MrDini123** [comment]
Nevermind. It was a libsodium bug. I modified the setup.py, and manually added "--disable-ssp" to the configure flags. I hope it will work now.
