### ISSUE TITLE
pip install pynacl doesn't work for Cygwin

### ISSUE THREAD

**Issue by Kitesurfer0** [pyca/pynacl#404]
Here is a log:

   CCLD     libaesni.la
  libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
  ar: unknown option -- u
  BusyBox v1.22.1 (2015-11-10 11:07:12    ) multi-call binary.

  Usage: ar [-o] [-v] [-p] [-t] [-x] ARCHIVE FILES

  Extract or list FILES from an ar archive

        -o      Preserve original dates
        -p      Extract to stdout
        -t      List
        -x      Extract
        -v      Verbose

  make[3]: *** [Makefile:1041: libaesni.la] Error 1
  make[3]: Leaving directory '/tmp/pip-build-asuglw3w/pynacl/build/temp.cygwin-2.8.2-i686-3.6/src/libsodium'
  make[2]: *** [Makefile:2925: all-recursive] Error 1
  make[2]: Leaving directory '/tmp/pip-build-asuglw3w/pynacl/build/temp.cygwin-2.8.2-i686-3.6/src/libsodium'
  make[1]: *** [Makefile:397: all-recursive] Error 1
  make[1]: Leaving directory '/tmp/pip-build-asuglw3w/pynacl/build/temp.cygwin-2.8.2-i686-3.6/src'
  make: *** [Makefile:513: all-recursive] Error 1
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-asuglw3w/pynacl/setup.py", line 251, in <module>
      "Programming Language :: Python :: 3.6",
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 199, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-asuglw3w/pynacl/setup.py", line 176, in run
      subprocess.check_call(["make"] + make_args, cwd=build_temp)
    File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.

  ----------------------------------------
  Failed building wheel for pynacl
  Running setup.py clean for pynacl
Failed to build pynacl

**Comment by draco1023** [comment]
I got the same error.

---

CCLD     libaesni.la
    libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
    ar: unknown option -- u
    BusyBox v1.22.1 (2015-11-10 11:07:12    ) multi-call binary.

    Usage: ar [-o] [-v] [-p] [-t] [-x] ARCHIVE FILES

    Extract or list FILES from an ar archive

        -o      Preserve original dates
        -p      Extract to stdout
        -t      List
        -x      Extract
        -v      Verbose

    make[3]: *** [Makefile:1041：libaesni.la] 错误 1
    make[3]: 离开目录“/tmp/pip-install-0j5mji/pynacl/build/temp.cygwin-2.8.2-i686-2.7/src/libsodium”
    make[2]: *** [Makefile:2925：all-recursive] 错误 1
    make[2]: 离开目录“/tmp/pip-install-0j5mji/pynacl/build/temp.cygwin-2.8.2-i686-2.7/src/libsodium”
    make[1]: *** [Makefile:397：all-recursive] 错误 1
    make[1]: 离开目录“/tmp/pip-install-0j5mji/pynacl/build/temp.cygwin-2.8.2-i686-2.7/src”
    make: *** [Makefile:513：all-recursive] 错误 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0j5mji/pynacl/setup.py", line 251, in <module>
        "Programming Language :: Python :: 3.6",
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-0j5mji/pynacl/setup.py", line 176, in run
        subprocess.check_call(["make"] + make_args, cwd=build_temp)
      File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2

    ----------------------------------------
Command "/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-0j5mji/pynacl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-aIXMdl/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-0j5mji/pynacl/

**Comment by reaperhulk** [comment]
Cygwin isn't a supported platform at this time. pynacl uses the libsodium makefile directly to build when a precompiled wheel is unavailable and that doesn't work under Cygwin. We would take a patch to add support, but that would probably either need to entirely rework how libsodium is compiled or be a PR to upstream libsodium.

**Comment by themiwi** [comment]
A bit late to the party, but: I am the maintainer of a Cygwin-package of pynacl (named `python2-nacl` and `python3-nacl`).

Since Cygwin already contains a package for `sodium`, the trick is to install with the exported `SODIUM_INSTALL=system` environment variable.

**Comment by reaperhulk** [comment]
Great to know! Thanks @themiwi, we'll direct people towards that when we can in the future
