### ISSUE TITLE
Command '['make', 'check']' returned non-zero exit status 2.

### ISSUE THREAD

**Issue by zhangxinZKCD** [pyca/pynacl#430]
I got a problem when installing PyNaCl inside docker（ubuntu:16.04）

**【os】**
root@f88665f270b3:/tmp/PyNaCl-1.2.1# uname -a
Linux f88665f270b3 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:22 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux

root@f88665f270b3:/tmp/PyNaCl-1.2.1# cat /proc/version
Linux version 4.4.0-87-generic (buildd@bos01-arm64-033) (gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) ) #110-Ubuntu SMP Tue Jul 18 12:55:22 UTC 2017

root@f88665f270b3:/tmp/PyNaCl-1.2.1# pip -V
pip 10.0.1 from /usr/local/python3.6/lib/python3.6/site-packages/pip (python 3.6)
root@f88665f270b3:/tmp/PyNaCl-1.2.1# python -V
Python 3.6.5

root@f88665f270b3:/tmp/PyNaCl-1.2.1# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/5/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 5.4.0-6ubuntu1 ~ 16.04.9'  --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-arm64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-arm64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-arm64 --with-arch-directory=aarch64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9) 

**【log】**
Makefile:515: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
Traceback (most recent call last):
  File "setup.py", line 254, in <module>
    "Programming Language :: Python :: 3.6",
  File "/usr/local/python3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/python3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/python3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/python3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/python3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/python3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 171, in run
    self.run_command('build_clib')
  File "/usr/local/python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 179, in run
    subprocess.check_call(["make", "check"] + make_args, cwd=build_temp)
  File "/usr/local/python3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'check']' returned non-zero exit status 2.

**The specific log is as follows:**
[log.txt](https://github.com/pyca/pynacl/files/1957260/log.txt)

**How can I solve this problem?**

**Comment by lmctv** [comment]
@zhangxinZKCD from the attached log, it seems the real problem is with libsodium proper: at line 673, there is a logged failure for `pwhash_scrypt`, and the report starting at line 678 says so:
```
============================================================================
Testsuite summary for libsodium 1.0.16
============================================================================
# TOTAL: 72
# PASS:  71
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See test/default/test-suite.log
Please report to https://github.com/jedisct1/libsodium/issues
============================================================================
Makefile:1804: recipe for target 'test-suite.log' failed
```
If at all possible, you should try and extract the `test/default/test-suite.log` file from your container storage, and look at what happened while running the failed test; as a wild guess, are you sure you didn't set too small memory limits on your container runtime?
