### ISSUE TITLE
Can not pip install from local dir

### ISSUE THREAD

**Issue by HibariMichiro** [pyca/pynacl#440]
I think it's similar to #321
Is setup_requires necessary in setup.py?

- Environment
```
# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
# uname -srvm
Linux 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64
# rpm -q python-setuptools
python-setuptools-0.9.8-7.el7.noarch
# pip -V
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
# python -V
Python 2.7.5
```
- Log(Fail)
```
# ls repo/
PyNaCl-1.2.1.tar.gz  cffi-1.11.2.tar.gz  pycparser-2.18.tar.gz  six-1.11.0.tar.gz
# pip install --no-index --find-links=repo PyNaCl
Ignoring indexes: https://pypi.python.org/simple
Collecting PyNaCl
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/cffi/: [Errno -2] Name or service not known -- Some packages may not be found!
    Couldn't find index page for 'cffi' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
    No local packages or download links found for cffi>=1.4.1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-z60R0t/PyNaCl/setup.py", line 251, in <module>
        "Programming Language :: Python :: 3.6",
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 617, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cffi>=1.4.1')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-z60R0t/PyNaCl/
```
- Log(Success)
```
# diff -Naurp PyNaCl-1.2.1.org PyNaCl-1.2.1
diff -Naurp PyNaCl-1.2.1.org/setup.py PyNaCl-1.2.1/setup.py
--- PyNaCl-1.2.1.org/setup.py   2017-12-04 17:30:26.000000000 +0900
+++ PyNaCl-1.2.1/setup.py       2018-06-13 10:18:15.521950500 +0900
@@ -38,7 +38,6 @@ except ImportError:


 requirements = ["six"]
-setup_requirements = []
 test_requirements = ["pytest>=3.2.1,!=3.3.0",
                      "hypothesis>=3.27.0"]
 docs_requirements = ["sphinx>=1.6.5",
@@ -53,7 +52,6 @@ if platform.python_implementation() == "
         )
 else:
     requirements.append("cffi>=1.4.1")
-    setup_requirements.append("cffi>=1.4.1")


 def here(*paths):
@@ -213,7 +211,6 @@ setup(

     author=nacl.__author__,
     author_email=nacl.__email__,
-    setup_requires=setup_requirements,
     install_requires=requirements,
     extras_require={
         "tests": test_requirements,

# pip install --no-index --find-links=repo PyNaCl
Ignoring indexes: https://pypi.python.org/simple
Collecting PyNaCl
Collecting six (from PyNaCl)
Collecting cffi>=1.4.1 (from PyNaCl)
Collecting pycparser (from cffi>=1.4.1->PyNaCl)
Installing collected packages: six, pycparser, cffi, PyNaCl
  Running setup.py install for six ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for cffi ... done
  Running setup.py install for PyNaCl ... done
Successfully installed PyNaCl-1.2.1 cffi-1.11.2 pycparser-2.18 six-1.11.0
```

**Comment by reaperhulk** [comment]
`cffi` needs to be present in `setup_requires` until we can drop support for pip versions that don't support `pyproject.toml`. So we can't remove it for now.

That said, your issue appears to be that setuptools couldn't find a route to pypi:
```
Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
```

`setup_requires` are processed by setuptools rather than pip (but only if the dependency isn't already present in your environment and you aren't installing from a wheel).
