### ISSUE TITLE
Support Aarch64

### ISSUE THREAD

**Issue by thetestgame** [pyca/pynacl#466]
Would it be possible to add support for aarch64 or what would be involved with adding support?

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ke3pd8xw/pynacl/setup.py", line 251, in <module>
        "Programming Language :: Python :: 3.6",
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1089, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

**Comment by reaperhulk** [comment]
I'm not sure why it wouldn't work assuming you're just running linux on aarch64 (libsodium should compile and cffi should work so pynacl should work). Unfortunately the traceback doesn't have any useful data in it. Could you try with a `pip install -vv pynacl`?

**Comment by lmctv** [comment]
From what I can see from debian's autobuilders log, at least version  1.2.1 was correctly built and passed its self tests on aarch64/arm64:
https://buildd.debian.org/status/fetch.php?pkg=python-nacl&arch=arm64&ver=1.2.1-3&stamp=1520984659&raw=0

**Comment by lmctv** [comment]
Could you please describe the build environment?

**Comment by lmctv** [comment]
From what I see, I think this is from an attempt a cross building.

**Comment by thetestgame** [comment]
I don't have the board to test anymore or get logs but I was attempting to build on a stock Ubuntu based Jetson TX1 board

**Comment by lmctv** [comment]
Within a correctly installed build environment, many versions of pynacl have been built under ubuntu/aarch64; the logs for the active releases are reachable from https://launchpad.net/ubuntu/+source/python-nacl

- https://launchpad.net/ubuntu/+source/python-nacl/1.0.1-1build1/+build/9003754/+files/buildlog_ubuntu-xenial-arm64.python-nacl_1.0.1-1build1_BUILDING.txt.gz
 - https://launchpad.net/ubuntu/+source/python-nacl/1.1.2-1build1/+build/14205812/+files/buildlog_ubuntu-bionic-arm64.python-nacl_1.1.2-1build1_BUILDING.txt.gz
- https://launchpad.net/ubuntu/+source/python-nacl/1.2.1-3build1/+build/15063724/+files/buildlog_ubuntu-cosmic-arm64.python-nacl_1.2.1-3build1_BUILDING.txt.gz

Closing.
