### ISSUE TITLE
Env vars are ignored when installing via pip

### ISSUE THREAD

**Issue by lovetox** [pyca/pynacl#497]
when installing on msys2 via pip, it seems pip ignores env vars

`$ SODIUM_INSTALL=system pip3 install pynacl` does not lead to system install

if i clone git and install via

`$ SODIUM_INSTALL=system python3 setup.py install`

it works fine

**Comment by alex** [comment]
Can you show the full output of the `pip install` version?

**Comment by lovetox** [comment]
you mean this

```
$ SODIUM_INSTALL=system pip3 install  pynacl
Collecting pynacl
  Using cached https://files.pythonhosted.org/packages/61/ab/2ac6dea8489fa713e2b4c6c5b549cc962dd4a842b5998d9e80cf8440b7cd/PyNaCl-1.3.0.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:/Users/user/AppData/Local/Temp/pip-build-env-roqpknaj/lib/python3.7/site-packages\setuptools\__init__.py", line 195, in <module>
        monkey.patch_all()
      File "C:/Users/user/AppData/Local/Temp/pip-build-env-roqpknaj/lib/python3.7/site-packages\setuptools\monkey.py", line 101, in patch_all
        patch_for_msvc_specialized_compiler()
      File "C:/Users/user/AppData/Local/Temp/pip-build-env-roqpknaj/lib/python3.7/site-packages\setuptools\monkey.py", line 164, in patch_for_msvc_specialized_compiler
        patch_func(*msvc9('find_vcvarsall'))
      File "C:/Users/user/AppData/Local/Temp/pip-build-env-roqpknaj/lib/python3.7/site-packages\setuptools\monkey.py", line 151, in patch_params
        mod = import_module(mod_name)
      File "C:/msys64/mingw32/lib/python3.7\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "C:/msys64/mingw32/lib/python3.7\distutils\msvc9compiler.py", line 296, in <module>
        raise DistutilsPlatformError("VC %0.1f is not supported by this module" % VERSION)
    distutils.errors.DistutilsPlatformError: VC 6.0 is not supported by this module

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:/Users/Philipp/AppData/Local/Temp/pip-install-mi4yspiy/pynacl/

```

**Comment by dbrgn** [comment]
Note that the docs explicitly recommend using `$ SODIUM_INSTALL=system pip install pynacl`:

https://pynacl.readthedocs.io/en/stable/install/#linux-source-build
