### ISSUE TITLE
Decrypting data with SealedBox(less than 48 bytes?) gives ValueError: negative array length 

### ISSUE THREAD

**Issue by ThePrzeglo** [pyca/pynacl#517]
Steps to reproduce:
```
python3.7 -m venv pynacl_test
source pynacl_test/bin/activate
pip install pynacl
python script.py # Code below
```

Code:
```
from nacl.public import PrivateKey, PublicKey, SealedBox
import nacl
import os

def trigger_bug_a():
    k = PrivateKey.generate()
    box = SealedBox(k)
    box.decrypt(b"")

def trigger_bug_b():
    for i in range(1000, 0, -1):
        try:
            k = PrivateKey.generate()
            box = SealedBox(k)
            box.decrypt(os.urandom(i))
        except nacl.exceptions.CryptoError: # Expected exception?
            pass
        except:
            print(f"Raised for i: {i}")
            raise

if __name__ == "__main__":
    trigger_bug_b()

if __name__ == "__main__":
    trigger_bug_b()
```
Result:
```
Raised for i: 47
Traceback (most recent call last):
  File "script.py", line 23, in <module>
    trigger_bug_b()
  File "script.py", line 15, in trigger_bug_b
    box.decrypt(os.urandom(i))
  File "/mnt/c/Users/John/Desktop/pynacl_test/lib/python3.7/site-packages/nacl/public.py", line 361, in decrypt
    self._private_key,
  File "/mnt/c/Users/John/Desktop/pynacl_test/lib/python3.7/site-packages/nacl/bindings/crypto_box.py", line 307, in crypto_box_seal_open
    plaintext = ffi.new("unsigned char[]", _mlen)
ValueError: negative array length
```

Tested on WSL with Python 3.7.1 (CPython)
pip freeze:
```
cffi==1.12.2
pkg-resources==0.0.0
pycparser==2.19
PyNaCl==1.3.0
six==1.12.0
```
I guess throwing exception from ffi is not intended behaviour.

**Comment by lmctv** [comment]
Thank you for the detailed bug report. I agree the exception should get raised *before* even trying to allocate the output buffer.

**Comment by lmctv** [comment]
@reaperhulk @pyca/pynacl-core: do you think we should we backport #518 and release a 1.3.1 version,or we could rely on a exception being already raised on too-short input and just close this issue?

**Comment by reaperhulk** [comment]
I don't think we need to backport. Let's triage a set of issues for a 1.4.0 milestone and see if we can't get that out the door in April though. I'll close this since it's now fixed in master.
