### ISSUE TITLE
Issues installing with Pip when not on the general internet

### ISSUE THREAD

**Issue by tpmullan** [pyca/pynacl#520]
When I try to install with pip from a vendor folder pynacl causes everything to fail even though all its dependencies will be met.  The main issue is the way dependencies are being set in this project.

Example of the issue
```
Collecting cffi>=1.4.1 (from -r /tmp/app/requirements/./base.txt (line 42))
          Collecting gunicorn==19.9.0 (from -r /tmp/app/requirements/production.txt (line 5))
          Collecting psycopg2==2.7.4 (from -r /tmp/app/requirements/production.txt (line 6))
          Collecting Unidecode>=0.04.16 (from python-slugify==1.2.6->-r /tmp/app/requirements/./base.txt (line 2))
          Collecting six (from argon2-cffi==18.3.0->-r /tmp/app/requirements/./base.txt (line 4))
          Collecting billiard<3.6.0,>=3.5.0.2 (from celery==4.2.1->-r /tmp/app/requirements/./base.txt (line 6))
          Collecting kombu<5.0,>=4.2.0 (from celery==4.2.1->-r /tmp/app/requirements/./base.txt (line 6))
          Collecting tornado>=4.2.0 (from flower==0.9.2->-r /tmp/app/requirements/./base.txt (line 7))
          Collecting babel>=1.0 (from flower==0.9.2->-r /tmp/app/requirements/./base.txt (line 7))
          Collecting python3-openid>=3.0.8 (from django-allauth==0.38.0->-r /tmp/app/requirements/./base.txt (line 14))
          Collecting requests-oauthlib>=0.3.0 (from django-allauth==0.38.0->-r /tmp/app/requirements/./base.txt (line 14))
          Collecting sqlparse>=0.2.0 (from django-debug-toolbar==1.10.1->-r /tmp/app/requirements/./base.txt (line 17))
          Collecting coreschema (from coreapi==2.3.3->-r /tmp/app/requirements/./base.txt (line 22))
          Collecting itypes (from coreapi==2.3.3->-r /tmp/app/requirements/./base.txt (line 22))
          Collecting uritemplate (from coreapi==2.3.3->-r /tmp/app/requirements/./base.txt (line 22))
          Collecting argcomplete>=1.0 (from python-libmaas==0.6.1->-r /tmp/app/requirements/./base.txt (line 26))
          Collecting colorclass>=1.2.0 (from python-libmaas==0.6.1->-r /tmp/app/requirements/./base.txt (line 26))
          Collecting macaroonbakery>=1.1.3 (from python-libmaas==0.6.1->-r /tmp/app/requirements/./base.txt (line 26))
          Collecting oauthlib>=1.0.3 (from python-libmaas==0.6.1->-r /tmp/app/requirements/./base.txt (line 26))
          Collecting pymongo>=3.5.1 (from python-libmaas==0.6.1->-r /tmp/app/requirements/./base.txt (line 26))
          Collecting terminaltables>=2.1.0 (from python-libmaas==0.6.1->-r /tmp/app/requirements/./base.txt (line 26))
          Collecting pyasn1>=0.3.7 (from python-ldap==3.1.0->-r /tmp/app/requirements/./base.txt (line 29))
          Collecting pyasn1_modules>=0.1.5 (from python-ldap==3.1.0->-r /tmp/app/requirements/./base.txt (line 29))
          Collecting chardet (from aiohttp==2.3.10->-r /tmp/app/requirements/./base.txt (line 33))
          Collecting multidict>=4.0.0 (from aiohttp==2.3.10->-r /tmp/app/requirements/./base.txt (line 33))
          Collecting async_timeout>=1.2.0 (from aiohttp==2.3.10->-r /tmp/app/requirements/./base.txt (line 33))
          Collecting yarl>=1.0.0 (from aiohttp==2.3.10->-r /tmp/app/requirements/./base.txt (line 33))
          Collecting idna-ssl>=1.0.0 (from aiohttp==2.3.10->-r /tmp/app/requirements/./base.txt (line 33))
          Collecting idna<2.9,>=2.5 (from requests==2.21.0->-r /tmp/app/requirements/./base.txt (line 34))
          Collecting urllib3<1.25,>=1.21.1 (from requests==2.21.0->-r /tmp/app/requirements/./base.txt (line 34))
          Collecting certifi>=2017.4.17 (from requests==2.21.0->-r /tmp/app/requirements/./base.txt (line 34))
          Collecting ntlm-auth>=1.0.2 (from requests_ntlm==1.1.0->-r /tmp/app/requirements/./base.txt (line 35))
          Collecting cryptography>=1.3 (from requests_ntlm==1.1.0->-r /tmp/app/requirements/./base.txt (line 35))
          Collecting bcrypt>=3.1.3 (from paramiko==2.4.2->-r /tmp/app/requirements/./base.txt (line 39))
          Collecting pynacl>=1.0.1 (from paramiko==2.4.2->-r /tmp/app/requirements/./base.txt (line 39))
              Complete output from command python setup.py egg_info:
              Download error on https://pypi.org/simple/cffi/: [Errno 97] Address family not supported by protocol -- Some packages may not be found!
              Couldn't find index page for 'cffi' (maybe misspelled?)
              Download error on https://pypi.org/simple/: [Errno 97] Address family not supported by protocol -- Some packages may not be found!
              No local packages or working download links found for cffi>=1.4.1
              Traceback (most recent call last):
                File "<string>", line 1, in <module>
                File "/tmp/pip-build-jddo036l/pynacl/setup.py", line 255, in <module>
                  "Programming Language :: Python :: 3.7",
                File "/tmp/contents693074633/deps/0/python/lib/python3.5/site-packages/setuptools-40.6.3-py3.5.egg/setuptools/__init__.py", line 142, in setup
                File "/tmp/contents693074633/deps/0/python/lib/python3.5/site-packages/setuptools-40.6.3-py3.5.egg/setuptools/__init__.py", line 137, in _install_setup_requires
                File "/tmp/contents693074633/deps/0/python/lib/python3.5/site-packages/setuptools-40.6.3-py3.5.egg/setuptools/dist.py", line 586, in fetch_build_eggs
                File "/tmp/contents693074633/deps/0/python/lib/python3.5/site-packages/setuptools-40.6.3-py3.5.egg/pkg_resources/__init__.py", line 780, in resolve
                File "/tmp/contents693074633/deps/0/python/lib/python3.5/site-packages/setuptools-40.6.3-py3.5.egg/pkg_resources/__init__.py", line 1063, in best_match
                File "/tmp/contents693074633/deps/0/python/lib/python3.5/site-packages/setuptools-40.6.3-py3.5.egg/pkg_resources/__init__.py", line 1075, in obtain
                File "/tmp/contents693074633/deps/0/python/lib/python3.5/site-packages/setuptools-40.6.3-py3.5.egg/setuptools/dist.py", line 653, in fetch_build_egg
                File "/tmp/contents693074633/deps/0/python/lib/python3.5/site-packages/setuptools-40.6.3-py3.5.egg/setuptools/command/easy_install.py", line 673, in easy_install
              distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cffi>=1.4.1')
```

**Comment by lmctv** [comment]
pynacl correctly exposes its dependency on cffi both at runtime and at build time at least since v0.3.0 times. I think this issue should be closed, since the projects consuming pynacl should ensure its dependencies are available.
