### ISSUE TITLE
 returned non-zero exit status 1.

### ISSUE THREAD

**Issue by ninjape** [pyca/pynacl#526]
python setup.py install
running install
running bdist_egg
running egg_info
writing src/PyNaCl.egg-info/PKG-INFO
writing dependency_links to src/PyNaCl.egg-info/dependency_links.txt
writing requirements to src/PyNaCl.egg-info/requires.txt
writing top-level names to src/PyNaCl.egg-info/top_level.txt
reading manifest file 'src/PyNaCl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__/*' found anywhere in distribution
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching '.travis'
warning: no previously-included files found matching '.travis/install.sh'
warning: no previously-included files found matching '.travis/run.sh'
warning: no previously-included files found matching '.readthedocs.yml'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching 'codecov.yml'
warning: no previously-included files found matching 'tasks.py'
warning: no previously-included files found matching 'Jenkinsfile'
warning: no previously-included files found matching '.jenkins'
warning: no previously-included files found matching '.jenkins/Jenkinsfile-pynacl-wheel-builder'
writing manifest file 'src/PyNaCl.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running build_clib
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... configure: error: unsafe srcdir value: '/root/python packages/PyNaCl-1.3.0/src/libsodium'
Traceback (most recent call last):
  File "setup.py", line 255, in <module>
    "Programming Language :: Python :: 3.7",
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 171, in run
    self.run_command('build_clib')
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 171, in run
    cwd=build_temp,
  File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/python packages/PyNaCl-1.3.0/src/libsodium/configure', '--disable-shared', '--enable-static', '--disable-debug', '--disable-dependency-tracking', '--with-pic', '--prefix', '/root/python packages/PyNaCl-1.3.0/build/temp.linux-x86_64-3.7']' returned non-zero exit status 1.

**Comment by lmctv** [comment]
The error is raised in the configure script of the bundled libsodium library; I'd suggest you try building as a regular user, and/or in a directory whose name doesn't contain whitespace characters and newlines. Closing, since this the problems with the bundled library are outside of our direct reach.
