### ISSUE TITLE
Issue installing PyNacl 1.3.0

### ISSUE THREAD

**Issue by prashanth-balaboina** [pyca/pynacl#554]
macOS High Sierra - 10.13.6
Python 2.7.0
setuptools 41.0.1

Collecting PyNaCl==1.3.0 (from -r /path/to/file/base_requirements.txt (line 128))
  Downloading /path/to/file/ext/tgz/PyNaCl-1.3.0.tar.gz (3.4MB)
     |████████████████████████████████| 3.4MB 4.6MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /path/to/file/bin/python2.7 /path/to/file/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/vy/sp26hff14r12g8myssqc8hvsgv6r8t/T/tmpbJWHnK
         cwd: /path/to/file/pip_builds/pip_build_0LWBid/PyNaCl
    Complete output (53 lines):
    running dist_info
    creating /path/to/file/pip_builds/pip_build_0LWBid/PyNaCl/pip-wheel-metadata/PyNaCl.egg-info
    writing requirements to /path/to/file/pip_builds/pip_build_0LWBid/PyNaCl/pip-wheel-metadata/PyNaCl.egg-info/requires.txt
    writing /path/to/file/pip_builds/pip_build_0LWBid/PyNaCl/pip-wheel-metadata/PyNaCl.egg-info/PKG-INFO
    writing top-level names to /path/to/file/pip_builds/pip_build_0LWBid/PyNaCl/pip-wheel-metadata/PyNaCl.egg-info/top_level.txt
    writing dependency_links to /path/to/file/pip_builds/pip_build_0LWBid/PyNaCl/pip-wheel-metadata/PyNaCl.egg-info/dependency_links.txt
    writing manifest file '/path/to/file/pip_builds/pip_build_0LWBid/PyNaCl/pip-wheel-metadata/PyNaCl.egg-info/SOURCES.txt'
    reading manifest file '/path/to/file/pip_builds/pip_build_0LWBid/PyNaCl/pip-wheel-metadata/PyNaCl.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '__pycache__/*' found anywhere in distribution
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/install.sh'
    warning: no previously-included files found matching '.travis/run.sh'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files found matching 'tasks.py'
    warning: no previously-included files found matching 'Jenkinsfile'
    warning: no previously-included files found matching '.jenkins'
    warning: no previously-included files found matching '.jenkins/Jenkinsfile-pynacl-wheel-builder'
    writing manifest file '/path/to/file/pip_builds/pip_build_0LWBid/PyNaCl/pip-wheel-metadata/PyNaCl.egg-info/SOURCES.txt'
    creating '/path/to/file/pip_builds/pip_build_0LWBid/PyNaCl/pip-wheel-metadata/PyNaCl.dist-info'
    Traceback (most recent call last):
      File "/path/to/file/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/path/to/file/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/path/to/file/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/vy/sp26hff14r12g8myssqc8hvsgv6r8t/T/pip-build-env-gh6O8V/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/private/var/folders/vy/sp26hff14r12g8myssqc8hvsgv6r8t/T/pip-build-env-gh6O8V/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 237, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/private/var/folders/vy/sp26hff14r12g8myssqc8hvsgv6r8t/T/pip-build-env-gh6O8V/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 255, in <module>
        "Programming Language :: Python :: 3.7",
      File "/private/var/folders/vy/sp26hff14r12g8myssqc8hvsgv6r8t/T/pip-build-env-gh6O8V/overlay/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Users/XXXXXX/.pyenv/versions/2.7.8/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/Users/XXXXXX/.pyenv/versions/2.7.8/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Users/XXXXXX/.pyenv/versions/2.7.8/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/vy/sp26hff14r12g8myssqc8hvsgv6r8t/T/pip-build-env-gh6O8V/overlay/lib/python2.7/site-packages/setuptools/command/dist_info.py", line 36, in run
        bdist_wheel.egg2dist(egg_info.egg_info, dist_info_dir)
      File "/private/var/folders/vy/sp26hff14r12g8myssqc8hvsgv6r8t/T/pip-build-env-gh6O8V/overlay/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 408, in egg2dist
        shutil.copy(license, os.path.join(self.distinfo_dir, license_filename))
      File "/path/to/file/lib/python2.7/posixpath.py", line 77, in join
        elif path == '' or path.endswith('/'):
    AttributeError: 'NoneType' object has no attribute 'endswith'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /path/to/file/bin/python2.7 /path/to/file/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/vy/sp26hff14r12g8myssqc8hvsgv6r8t/T/tmpbJWHnK Check the logs for full command output.

Can some please guide me through this? Thanks

**Comment by reaperhulk** [comment]
Create a fresh virtualenv with the latest pip and you should get a wheel.
