### ISSUE TITLE
Error when used with minimal build of libsodium

### ISSUE THREAD

**Issue by jefferyto** [pyca/pynacl#588]
Hi, I'm helping with someone packaging PyNaCl for OpenWrt and it appears that PyNaCl will try to use scrypt even when libsodium is compiled with `--enable-minimal`.

Run-time log from https://github.com/openwrt/packages/pull/11364#issuecomment-608080207:

```
root@8b6ad2613646:/# python3
Python 3.8.2 (default, Apr 02 2020, 02:06:15)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nacl
>>> import nacl.hash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hash.py", line 22, in <module>
  File "/__init__.py", line 17, in <module>
  File "/crypto_aead.py", line 18, in <module>
ImportError: Error relocating /usr/lib/python3.8/site-packages/nacl/_sodium.abi3.so: crypto_pwhash_scryptsalsa208sha256_memlimit_interactive: symbol not found
>>>
```

I also see implicit declaration warnings during package build:

```
running build_ext
generating cffi module 'build/temp.linux2-3.8/_sodium.c'
creating build/temp.linux2-3.8
building '_sodium' extension
creating build/temp.linux2-3.8/build
creating build/temp.linux2-3.8/build/temp.linux2-3.8
aarch64-openwrt-linux-musl-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/build_dir/target-aarch64_generic_musl/Python-3.8.2=Python-3.8.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/build_dir/target-aarch64_generic_musl/Python-3.8.2=Python-3.8.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DNDEBUG -fno-inline -Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/build_dir/target-aarch64_generic_musl/Python-3.8.2=Python-3.8.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DNDEBUG -fno-inline -I/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/target-aarch64_generic_musl/usr/include -I/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/usr/include -I/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/include/fortify -I/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/include -Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/build_dir/target-aarch64_generic_musl/pypi/python-pynacl-python3/PyNaCl-1.3.0=PyNaCl-1.3.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/target-aarch64_generic_musl/usr/include -I/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/usr/include -I/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/include/fortify -I/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/include -I/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/target-aarch64_generic_musl/usr/include/python3.8 -fPIC -I/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/target-aarch64_generic_musl/usr/include/python3.8 -c build/temp.linux2-3.8/_sodium.c -o build/temp.linux2-3.8/build/temp.linux2-3.8/_sodium.o
cc1: note: someone does not honour COPTS correctly, passed 4 times
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_bytes_max':
build/temp.linux2-3.8/_sodium.c:5093:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_bytes_max'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_bytes_max'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_bytes_max();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_bytes_max
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_bytes_min':
build/temp.linux2-3.8/_sodium.c:5119:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_bytes_min'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_bytes_min'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_bytes_min();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_bytes_min
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_ll':
build/temp.linux2-3.8/_sodium.c:5145:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_ll'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_ll'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_ll(x0, x1, x2, x3, x4, x5, x6, x7, x8);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_ll
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_memlimit_interactive':
build/temp.linux2-3.8/_sodium.c:5245:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_memlimit_interactive'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_memlimit_interactive'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_memlimit_interactive();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_memlimit_interactive
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_memlimit_max':
build/temp.linux2-3.8/_sodium.c:5271:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_memlimit_max'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_memlimit_max'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_memlimit_max();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_memlimit_max
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_memlimit_min':
build/temp.linux2-3.8/_sodium.c:5297:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_memlimit_min'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_memlimit_min'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_memlimit_min();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_memlimit_min
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive':
build/temp.linux2-3.8/_sodium.c:5323:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_opslimit_interactive':
build/temp.linux2-3.8/_sodium.c:5349:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_opslimit_interactive'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_opslimit_interactive'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_opslimit_interactive();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_opslimit_interactive
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_opslimit_max':
build/temp.linux2-3.8/_sodium.c:5375:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_opslimit_max'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_opslimit_max'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_opslimit_max();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_opslimit_max
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_opslimit_min':
build/temp.linux2-3.8/_sodium.c:5401:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_opslimit_min'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_opslimit_min'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_opslimit_min();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_opslimit_min
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive':
build/temp.linux2-3.8/_sodium.c:5427:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_passwd_max':
build/temp.linux2-3.8/_sodium.c:5453:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_passwd_max'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_passwd_max'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_passwd_max();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_passwd_max
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_passwd_min':
build/temp.linux2-3.8/_sodium.c:5479:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_passwd_min'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_passwd_min'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_passwd_min();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_passwd_min
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_saltbytes':
build/temp.linux2-3.8/_sodium.c:5505:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_saltbytes'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_saltbytes'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_saltbytes();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_saltbytes
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_str':
build/temp.linux2-3.8/_sodium.c:5531:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_str'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_str'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_str(x0, x1, x2, x3, x4);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_str
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_str_verify':
build/temp.linux2-3.8/_sodium.c:5602:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_str_verify'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_str_verify'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_str_verify(x0, x1, x2);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_str_verify
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_strbytes':
build/temp.linux2-3.8/_sodium.c:5661:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_strbytes'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_strbytes'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_strbytes();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_strbytes
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_pwhash_scryptsalsa208sha256_strprefix':
build/temp.linux2-3.8/_sodium.c:5687:10: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256_strprefix'; did you mean '_cffi_d_crypto_pwhash_scryptsalsa208sha256_strprefix'? [-Wimplicit-function-declaration]
   return crypto_pwhash_scryptsalsa208sha256_strprefix();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_crypto_pwhash_scryptsalsa208sha256_strprefix
build/temp.linux2-3.8/_sodium.c:5687:10: warning: returning 'int' from a function with return type 'const char *' makes pointer from integer without a cast [-Wint-conversion]
   return crypto_pwhash_scryptsalsa208sha256_strprefix();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
build/temp.linux2-3.8/_sodium.c: In function '_cffi_f_crypto_pwhash_scryptsalsa208sha256_strprefix':
build/temp.linux2-3.8/_sodium.c:5698:12: warning: assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
   { result = crypto_pwhash_scryptsalsa208sha256_strprefix(); }
            ^
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_shorthash_siphashx24':
build/temp.linux2-3.8/_sodium.c:7185:10: warning: implicit declaration of function 'crypto_shorthash_siphashx24'; did you mean 'crypto_shorthash_siphash24'? [-Wimplicit-function-declaration]
   return crypto_shorthash_siphashx24(x0, x1, x2, x3);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
          crypto_shorthash_siphash24
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_shorthash_siphashx24_bytes':
build/temp.linux2-3.8/_sodium.c:7255:10: warning: implicit declaration of function 'crypto_shorthash_siphashx24_bytes'; did you mean 'crypto_shorthash_siphash24_bytes'? [-Wimplicit-function-declaration]
   return crypto_shorthash_siphashx24_bytes();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          crypto_shorthash_siphash24_bytes
build/temp.linux2-3.8/_sodium.c: In function '_cffi_d_crypto_shorthash_siphashx24_keybytes':
build/temp.linux2-3.8/_sodium.c:7281:10: warning: implicit declaration of function 'crypto_shorthash_siphashx24_keybytes'; did you mean 'crypto_shorthash_siphash24_keybytes'? [-Wimplicit-function-declaration]
   return crypto_shorthash_siphashx24_keybytes();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          crypto_shorthash_siphash24_keybytes
aarch64-openwrt-linux-musl-gcc -shared -L/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/target-aarch64_generic_musl/usr/lib -L/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/target-aarch64_generic_musl/lib -L/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/usr/lib -L/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/lib -znow -zrelro -lpython3.8 -Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/build_dir/target-aarch64_generic_musl/pypi/python-pynacl-python3/PyNaCl-1.3.0=PyNaCl-1.3.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/target-aarch64_generic_musl/usr/include -I/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/usr/include -I/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/include/fortify -I/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/include -I/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/target-aarch64_generic_musl/usr/include/python3.8 build/temp.linux2-3.8/build/temp.linux2-3.8/_sodium.o -L/media/jeff/Jekyll/Files/openwrt/testing/armvirt-64/staging_dir/target-aarch64_generic_musl/usr/lib -lsodium -o build/lib.linux2-3.8/nacl/_sodium.abi3.so
```

**Comment by reaperhulk** [comment]
I would be willing to take a patch that skips these tests, raises an error if you try to use the unsupported functions at runtime, and properly detects if the underlying libsodium is built in this fashion. We'd also need to add a new builder to the CI that builds libsodium with this flag to ensure we don't regress.

**Comment by jefferyto** [comment]
I'm looking into it, but I have a question: what version(s) of libsodium does this project officially support? I don't think I've seen any version/API testing in the code so I would assume only the bundled version (and perhaps newer) is supported.
