### ISSUE TITLE
pynacl 1.4.0 fails pip install

### ISSUE THREAD

**Issue by almynamswertakn** [pyca/pynacl#591]
C:\Users\Drew\PycharmProjects\discord_bot>pip --version
pip 20.1.1 from c:\users\drew\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)

C:\Users\Drew\PycharmProjects\discord_bot>pip install pynacl -U
Collecting pynacl
  Using cached PyNaCl-1.4.0.tar.gz (3.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied, skipping upgrade: six in c:\users\drew\appdata\local\programs\python\python38\lib\site-packages (fro
m pynacl) (1.15.0)
Requirement already satisfied, skipping upgrade: cffi>=1.4.1 in c:\users\drew\appdata\local\programs\python\python38\lib\site-packa
ges (from pynacl) (1.14.0)
Requirement already satisfied, skipping upgrade: pycparser in c:\users\drew\appdata\local\programs\python\python38\lib\site-package
s (from cffi>=1.4.1->pynacl) (2.20)
Building wheels for collected packages: pynacl
  Building wheel for pynacl (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\drew\appdata\local\programs\python\python38\python.exe' 'c:\users\drew\appdata\local\programs\python\python38
\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\Drew\AppData\Local\Temp\tmpyhixzqwu'
       cwd: C:\Users\Drew\AppData\Local\Temp\pip-install-ged67tzw\pynacl
  Complete output (77 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\nacl
  copying src\nacl\encoding.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\exceptions.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\hash.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\hashlib.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\public.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\secret.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\signing.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\utils.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\__init__.py -> build\lib.win-amd64-3.8\nacl
  creating build\lib.win-amd64-3.8\nacl\pwhash
  copying src\nacl\pwhash\argon2i.py -> build\lib.win-amd64-3.8\nacl\pwhash
  copying src\nacl\pwhash\argon2id.py -> build\lib.win-amd64-3.8\nacl\pwhash
  copying src\nacl\pwhash\scrypt.py -> build\lib.win-amd64-3.8\nacl\pwhash
  copying src\nacl\pwhash\_argon2.py -> build\lib.win-amd64-3.8\nacl\pwhash
  copying src\nacl\pwhash\__init__.py -> build\lib.win-amd64-3.8\nacl\pwhash
  creating build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_aead.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_box.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_core.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_generichash.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_hash.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_kx.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_pwhash.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_scalarmult.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_secretbox.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_secretstream.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_shorthash.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_sign.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\randombytes.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\sodium_core.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\utils.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\__init__.py -> build\lib.win-amd64-3.8\nacl\bindings
  running build_clib
  Traceback (most recent call last):
    File "c:\users\drew\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <
module>
      main()
    File "c:\users\drew\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in m
ain
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\drew\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 204, in b
uild_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\Drew\AppData\Local\Temp\pip-build-env-4ad01uu9\overlay\Lib\site-packages\setuptools\build_meta.py", line 212, in
 build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\Drew\AppData\Local\Temp\pip-build-env-4ad01uu9\overlay\Lib\site-packages\setuptools\build_meta.py", line 198, in
 _build_with_temp_dir
      self.run_setup()
    File "C:\Users\Drew\AppData\Local\Temp\pip-build-env-4ad01uu9\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in
 run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 216, in <module>
      setup(
    File "C:\Users\Drew\AppData\Local\Temp\pip-build-env-4ad01uu9\overlay\Lib\site-packages\setuptools\__init__.py", line 144, in s
etup
      return distutils.core.setup(**attrs)
    File "c:\users\drew\appdata\local\programs\python\python38\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\drew\appdata\local\programs\python\python38\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\drew\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Drew\AppData\Local\Temp\pip-build-env-4ad01uu9\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 223, in run

      self.run_command('build')
    File "c:\users\drew\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\drew\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\drew\appdata\local\programs\python\python38\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\drew\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\drew\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 161, in run
      raise Exception("ERROR: The 'make' utility is missing from PATH")
  Exception: ERROR: The 'make' utility is missing from PATH
  ----------------------------------------
  ERROR: Failed building wheel for pynacl
Failed to build pynacl
ERROR: Could not build wheels for pynacl which use PEP 517 and cannot be installed directly

**Comment by newAM** [comment]
Looks like the CI failed for Windows as well.  I just rolled back to `1.3.0` for now.

**Comment by reaperhulk** [comment]
This was because we hadn’t published wheels yet. Should be fixed now.
