### ISSUE TITLE
PyNaCl on a docker

### ISSUE THREAD

**Issue by Donrskbb** [pyca/pynacl#625]
How to get PyNaCl working on a docker/container?
Idk what to do anymore. All bots just doesnt reconise the lib.

**Comment by alex** [comment]
You pip install it as you would any other python library. It's likely you'd need to update your pip or virtualenv or setuptools.

If you can provide an error message we might be able to explain it, but this is not actionable at the moment so I'm going to close it.

**Comment by Donrskbb** [comment]
This is the error
```py
Guild List:
- Casual_Gaming_Dad
Bound to text channels:
- Casual_Gaming_Dad/🎶┃muziek-aanvragen
Autojoining voice channels:
- Casual_Gaming_Dad/🎶┃ Lounge
Attempting to join Casual_Gaming_Dad/🎶┃ Lounge
[ERROR:bot] Failed to join Casual_Gaming_Dad/🎶┃ Lounge
427717508359782400/Donrskbb # 0007: -summon
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
File "/home/container/musicbot/bot.py", line 2815, in on_message
response = await handler(**handler_kwargs)
File "/home/container/musicbot/bot.py", line 1929, in cmd_summon
player = await self.get_player(author.voice.channel, create=True, deserialize=self.config.persistent_queue)
File "/home/container/musicbot/bot.py", line 421, in get_player
voice_client = await self.get_voice_client(channel)
File "/home/container/musicbot/bot.py", line 386, in get_voice_client
return await channel.connect(timeout=60, reconnect=True)
File "/home/container/discord/abc.py", line 1097, in connect
voice = VoiceClient(state=state, timeout=timeout, channel=self)
File "/home/container/discord/voice_client.py", line 90, in __init__
raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice```

And as you can see PyNaCl is installed:
![image](https://user-images.githubusercontent.com/65772844/92934421-c1d46900-f447-11ea-896f-b1601ceda93e.png)
