### ISSUE TITLE
Unable to install pynacl using pypy v3.8.12

### ISSUE THREAD

**Issue by EpicBirb** [pyca/pynacl#734]
As the tittle says.

Logs:
```
Collecting pynacl
  Downloading PyNaCl-1.4.0.tar.gz (3.4 MB)
     |████████████████████████████████| 3.4 MB 3.2 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: pynacl
  Building wheel for pynacl (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\[REDACTED]\AppData\Local\Programs\pypy3.8\pypy.exe' 'C:\Users\[REDACTED]\AppData\Local\Programs\pypy3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\[REDACTED]\AppData\Local\Temp\tmpozcy2ufk'
       cwd: C:\Users\[REDACTED]\AppData\Local\Temp\pip-install-7ktjlubl\pynacl_2abb5d4b708644059cddbc1d3bb72230
  Complete output (79 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\nacl
  copying src\nacl\encoding.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\exceptions.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\hash.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\hashlib.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\public.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\secret.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\signing.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\utils.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\__init__.py -> build\lib.win-amd64-3.8\nacl
  creating build\lib.win-amd64-3.8\nacl\pwhash
  copying src\nacl\pwhash\argon2i.py -> build\lib.win-amd64-3.8\nacl\pwhash
  copying src\nacl\pwhash\argon2id.py -> build\lib.win-amd64-3.8\nacl\pwhash
  copying src\nacl\pwhash\scrypt.py -> build\lib.win-amd64-3.8\nacl\pwhash
  copying src\nacl\pwhash\_argon2.py -> build\lib.win-amd64-3.8\nacl\pwhash
  copying src\nacl\pwhash\__init__.py -> build\lib.win-amd64-3.8\nacl\pwhash
  creating build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_aead.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_box.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_core.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_generichash.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_hash.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_kx.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_pwhash.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_scalarmult.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_secretbox.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_secretstream.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_shorthash.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_sign.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\randombytes.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\sodium_core.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\utils.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\__init__.py -> build\lib.win-amd64-3.8\nacl\bindings
  running build_clib
  Traceback (most recent call last):
    File "C:\Users\[REDACTED]\AppData\Local\Programs\pypy3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "C:\Users\[REDACTED]\AppData\Local\Programs\pypy3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\[REDACTED]\AppData\Local\Programs\pypy3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 262, in build_wheel
      metadata_directory)
    File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-94tml62m\overlay\Lib\site-packages\setuptools\build_meta.py", line 231, in build_wheel
      wheel_directory, config_settings)
    File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-94tml62m\overlay\Lib\site-packages\setuptools\build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-94tml62m\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 264, in <module>
      "Programming Language :: Python :: 3.8",
    File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-94tml62m\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-94tml62m\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      return run_commands(dist)
    File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-94tml62m\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
      dist.run_commands()
    File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-94tml62m\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-94tml62m\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-94tml62m\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-94tml62m\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-94tml62m\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-94tml62m\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-94tml62m\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-94tml62m\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "setup.py", line 161, in run
      raise Exception("ERROR: The 'make' utility is missing from PATH")
  Exception: ERROR: The 'make' utility is missing from PATH
  ----------------------------------------
  ERROR: Failed building wheel for pynacl
Failed to build pynacl
ERROR: Could not build wheels for pynacl, which is required to install pyproject.toml-based projects
```

**Comment by reaperhulk** [comment]
Do you have `make` and a compiler installed? The error msg indicates that you don't: `  Exception: ERROR: The 'make' utility is missing from PATH`

**Comment by reaperhulk** [comment]
Since you're on Windows this will be very challenging, unfortunately, but this project has no plans to ship pypy wheels for Windows at this time. You can look at our GitHub Actions wheel builder scripts to see how we compile on Windows (we use prebuilt binaries to avoid the `make` requirement)

**Comment by EpicBirb** [comment]
Ok, thanks for the information
