### ISSUE TITLE
Failed building wheel for PyNaCl (termux)

### ISSUE THREAD

**Issue by ssr765** [pyca/pynacl#773]
when i try to install PyNaCl on Termux i get this error

![IMG_20220922_230915](https://user-images.githubusercontent.com/64972770/191852550-d681ed51-180c-44c5-a3f4-653bc05cd7a3.jpg)

**Comment by alex** [comment]
It's a bit hard to tell what's going on from this truncated output. Can you please provide the complete command and output, as text (not an image)?

**Comment by ssr765** [comment]
> 

yeah sure
https://pastebin.com/wXPqiKSn

**Comment by alex** [comment]
from the log:

```
      checking for ld used by aarch64-linux-android-clang... no
      configure: error: no acceptable ld found in $PATH
```

**Comment by ssr765** [comment]
Command and complete output: https://pastebin.com/3NFfArQs

**Comment by firobeid** [comment]
Also pyodide.asm.js:10 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 359, in run_async
    await coroutine
  File "<exec>", line 3, in <module>
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 552, in install
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for: 'pynacl>=1.3.0'

**Comment by firobeid** [comment]
Is there a none or wasm wheel?

**Comment by reaperhulk** [comment]
You’ll have to talk to the pyiodide folks about that. We do not ship wasm wheels (and it is not possible to ship pure Python given our libsodium dependency).
